spring:
  mvc:
#    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: [classpath:/haha/]
      add-mappings: true
      cache:
        period: 11000
